<?php

namespace D3CR33\Panel\Http\Controllers;

use D3CR33\Auth\Base\Model\User;
use D3CR33\Panel\Base\BaseEntity;
use Illuminate\Http\Request;

/**
 * Class UserController
 * @package D3CR33\Panel\Http\Controllers
 */
class UserController extends BaseEntity
{
    /**
     * UserController constructor.
     *
     * @param  User  $user
     */
    public function __construct(User $user, Request $request)
    {
        $this->model = $user;
        $this->request = $request;
    }
    public function create($param)
    {
        return parent::create($param); // TODO: Change the autogenerated stub
    }
    public function update($id, $param)
    {
        return parent::update($id, $param); // TODO: Change the autogenerated stub
    }

}
